# Generated by Django 3.2.13 on 2022-05-16 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffeeblog', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cooking_length',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpost_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
