# Generated by Django 3.2.13 on 2022-05-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0003_auto_20220516_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cooking_length',
        ),
    ]
