# Generated by Django 3.2.13 on 2022-05-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0004_remove_post_cooking_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='prepration_length',
            field=models.IntegerField(default=0),
        ),
    ]
