# Generated by Django 3.2.13 on 2022-05-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0005_auto_20220518_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='prepration_length',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
