# Generated by Django 3.2.13 on 2022-05-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0006_auto_20220518_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='method',
        ),
    ]
