# Generated by Django 3.2.13 on 2022-05-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0007_rename_content_post_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
