# Generated by Django 3.2.13 on 2022-05-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0011_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
