# Generated by Django 3.2.13 on 2022-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeblog', '0015_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='method',
        ),
    ]
